services:
  docs:
    image: cookie_pro_local_docs
    container_name: cookie_pro_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cookie_pro:/app/cookie_pro:z
    ports:
      - '9000:9000'
    command: /start-docs
