volumes:
  cookiecutter_django_local_postgres_data: {}
  cookiecutter_django_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cookiecutter_django_local_django
    container_name: cookiecutter_django_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    image: postgres:17
    container_name: cookiecutter_django_local_postgres
    volumes:
      - cookiecutter_django_local_postgres_data:/var/lib/postgresql/data
      - cookiecutter_django_local_postgres_data_backups:/backups
    environment:
      - POSTGRES_DB=cookie_pro
      - POSTGRES_USER=sadegh
      - POSTGRES_PASSWORD=ms@155222
    ports:
      - '5433:5432'

  redis:
    image: redis:6
    container_name: cookiecutter_django_local_redis

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: cookiecutter_django_local_node
    container_name: cookiecutter_django_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
